server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # 开启从注册中心动态创建路由的功能, 李勇微服务名进行路由
      routes:
        - id: payment_routh #payment_route # 路由的ID， 没有固定规则但要求唯一, 建议配合服务名
#          uri: http://localhost:8001 # 匹配后提供服务的路由地址
          uri: lb://CLOUD-PAYMENT-SERVER # 匹配后提供服务的路由地址
          predicates:
            - Path=/payment/get/** # 断言,路径相匹配的进行路由
            - After=2021-07-21T23:23:50.842+08:00[GMT+08:00]
            - Cookie=username,zzyy # curl http://localhost:9527/payment/lb --cookie "username=zzyy"
            - Header=X-Request-Id,\d+ # 请求头要求要有X-Request-Id属性并且值为整数的正则表达式 curl http://localhost:9527/payment/lb --cookie "username=zzyy" -H "X-Request-Id:123"
#            - Method=GET
        - id: payment_routh2
#          uri: http://localhost:8001
          uri: lb://CLOUD-PAYMENT-SERVER
          predicates:
            - Path=/payment/lb/**
            - After=2021-07-21T23:23:50.842+08:00[GMT+08:00]
            - Cookie=username,zzyy # curl http://localhost:9527/payment/lb --cookie "username=zzyy"
            - Header=X-Request-Id,\d+ # 请求头要求要有X-Request-Id属性并且值为整数的正则表达式 curl http://localhost:9527/payment/lb --cookie "username=zzyy" -H "X-Request-Id:123"
#            - Method=GET

eureka:
  client:
    # 表示是否将自己注册进EurekaServer 默认为true
    register-with-eureka: true
    # 是否从EurekaServer 抓去自己的注册信息, 默认为true, 单节点无所谓，
    # 集群必需设置为true 才能配合ribbon 使用负载均衡
    fetch-registry: true
    service-url:
      # 设置与Eureka Server 交互的地址查询服务和注册服务都需要依赖这个地址
      #defaultZone: http://localhost:7002/eureka/ # 单机版
      defaultZone: http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/ # 集群模式

#设置feign客户端调用接口超时时间(OpenFeign 默认支持Ribbon)
ribbon:
  #指的是建立连接所用的时间, 适用于网络状况正常的情况下, 两端连接所调用的时间
  ReadTimeout: 5000
  #指的是建立连接后从服务器读取到可用资源所用的时间
  ConnectTimeout: 5000

logging:
  level:
    # feign 日志以什么级别监控哪个接口
    com.springcloud.service.PaymentFeignService: debug
