server:
  port: 80


eureka:
  client:
    # 表示是否将自己注册进EurekaServer 默认为true
    register-with-eureka: true
    # 是否从EurekaServer 抓去自己的注册信息, 默认为true, 单节点无所谓，
    # 集群必需设置为true 才能配合ribbon 使用负载均衡
    fetch-registry: true
    service-url:
      # 设置与Eureka Server 交互的地址查询服务和注册服务都需要依赖这个地址
      #defaultZone: http://localhost:7002/eureka/ # 单机版
      defaultZone: http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/ # 集群模式

#设置feign客户端调用接口超时时间(OpenFeign 默认支持Ribbon)
ribbon:
  #指的是建立连接所用的时间, 适用于网络状况正常的情况下, 两端连接所调用的时间
  ReadTimeout: 5000
  #指的是建立连接后从服务器读取到可用资源所用的时间
  ConnectTimeout: 5000

logging:
  level:
    # feign 日志以什么级别监控哪个接口
    com.springcloud.service.PaymentFeignService: debug