spring:
  application:
    name: cloud-canal-clent
    #配置rabbitMq 服务器
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: canal
    password: canal
    #虚拟host 可以不设置,使用server默认host
    virtual-host: canal_vhost # canal_vhost
    connection-timeout: 15000
#    listener:
#      # 表示消费者消费成功消息以后需要手工的进行签收(ack)，默认为auto
#      simple:
#        acknowledge-mode: manual
#        concurrency: 5
#        max-concurrency: 10
#        prefetch: 1

# 用于配置 CanalServer是使用什么模式进行推送
#canalClientType: rabbitMQ